/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApiKey } from "./apikey";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class ApiKeyResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => ApiKey)
    data: ApiKey;
}
