/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApiKey } from "./apikey";
import { Expose, Type } from "class-transformer";

/**
 * Request body for creating a single API key.
 */
export class ApiKeyCreateBody extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "api_key" })
  @Type(() => ApiKey)
  apiKey: ApiKey;
}
