/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { JsonPatchElement } from "./jsonpatchelement";
import { Expose, Type } from "class-transformer";

/**
 * Request body for updating a single API key.
 */
export class ApiKeyJsonPatchBody extends SpeakeasyBase {
    /**
     * JSON Patch document for schema `ApiKey`.
     */
    @SpeakeasyMetadata({ elemType: JsonPatchElement })
    @Expose({ name: "api_key" })
    @Type(() => JsonPatchElement)
    apiKey: JsonPatchElement[];
}
