/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApiKey } from "./apikey";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class ApiKeysPaged extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ApiKey })
    @Expose({ name: "data" })
    @Type(() => ApiKey)
    data: ApiKey[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    meta: Record<string, any>;
}
