/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApiKeyOptions } from "./apikeyoptions";
import { Expose, Type } from "class-transformer";

/**
 * Request body for updating a single API key.
 */
export class ApiKeyUpdateBody extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "api_key" })
  @Type(() => ApiKeyOptions)
  apiKey: ApiKeyOptions;
}
