/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ContractMonths } from "./contractmonths";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class ContractMonthsList extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ContractMonths })
    @Expose({ name: "data" })
    @Type(() => ContractMonths)
    data: ContractMonths[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    meta: Record<string, any>;
}
