/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ContractQuarters } from "./contractquarters";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class ContractQuartersResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => ContractQuarters)
    data: ContractQuarters;
}
