/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ContractMonths } from "./contractmonths";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class ContractMonthsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  @Type(() => ContractMonths)
  data: ContractMonths;
}
