/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Contract } from "./contract";
import { Expose, Type } from "class-transformer";

/**
 * Request body for creating a single contract.
 */
export class ContractCreateBody extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "contract" })
  @Type(() => Contract)
  contract: Contract;
}
