/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ContractOptions } from "./contractoptions";
import { Expose, Type } from "class-transformer";

/**
 * Request body for updating a single contract.
 */
export class ContractUpdateBody extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "contract" })
  @Type(() => ContractOptions)
  contract: ContractOptions;
}
