/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Contract } from "./contract";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class ContractsPaged extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Contract })
    @Expose({ name: "data" })
    @Type(() => Contract)
    data: Contract[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    meta: Record<string, any>;
}
