/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { JsonPatchElement } from "./jsonpatchelement";
import { Expose, Type } from "class-transformer";

/**
 * Request body for updating a single customer.
 */
export class CustomerJsonPatchBody extends SpeakeasyBase {
    /**
     * JSON Patch document for schema `Customer`.
     */
    @SpeakeasyMetadata({ elemType: JsonPatchElement })
    @Expose({ name: "customer" })
    @Type(() => JsonPatchElement)
    customer: JsonPatchElement[];
}
