/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Customer } from "./customer";
import { Expose, Type } from "class-transformer";

/**
 * Request body for creating a single customer.
 */
export class CustomerCreateBody extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "customer" })
  @Type(() => Customer)
  customer: Customer;
}
