/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TenantsIdOnly } from "./tenantsidonly";
import { Expose, Transform, Type } from "class-transformer";

export class CustomerOptions extends SpeakeasyBase {
  /**
   * Soft-delete timestamp.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "deleted_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  deletedAt?: Date;

  /**
   * Customer primary contact.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "email" })
  email: string;

  /**
   * Customer ID.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Customer name.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * The customers tax ID.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "tax_id" })
  taxId: string;

  @SpeakeasyMetadata()
  @Expose({ name: "tenant" })
  @Type(() => TenantsIdOnly)
  tenant?: TenantsIdOnly;

  /**
   * Last updated timestamp.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updated_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt?: Date;
}
