/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Customer } from "./customer";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class CustomersList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: Customer })
  @Expose({ name: "data" })
  @Type(() => Customer)
  data: Customer[];

  @SpeakeasyMetadata()
  @Expose({ name: "meta" })
  meta: Record<string, any>;
}
