/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CustomerOptions } from "./customeroptions";
import { Expose, Type } from "class-transformer";

/**
 * Request body for updating a single customer.
 */
export class CustomerUpdateBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "customer" })
    @Type(() => CustomerOptions)
    customer: CustomerOptions;
}
