/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CustomersIdOnly extends SpeakeasyBase {
  /**
   * Customer ID.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;
}
