/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EquipmentType } from "./equipmenttype";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class EquipmentTypeResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => EquipmentType)
    data: EquipmentType;
}
