/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EquipmentOptions } from "./equipmentoptions";
import { Expose, Type } from "class-transformer";

/**
 * Request body for updating a single equipment.
 */
export class EquipmentUpdateBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "equipment" })
    @Type(() => EquipmentOptions)
    equipment: EquipmentOptions;
}
