/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EquipmentType } from "./equipmenttype";
import { Expose, Type } from "class-transformer";

/**
 * Request body for creating a single equipment type.
 */
export class EquipmentTypeCreateBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "equipment_type" })
    @Type(() => EquipmentType)
    equipmentType: EquipmentType;
}
