/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EquipmentTypeOptions } from "./equipmenttypeoptions";
import { Expose, Type } from "class-transformer";

/**
 * Request body for updating a single equipment type.
 */
export class EquipmentTypeUpdateBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "equipment_type" })
    @Type(() => EquipmentTypeOptions)
    equipmentType: EquipmentTypeOptions;
}
