/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Equipment } from "./equipment";
import { Expose, Type } from "class-transformer";

/**
 * Request body for creating a single equipment.
 */
export class EquipmentCreateBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "equipment" })
    @Type(() => Equipment)
    equipment: Equipment;
}
