/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GroupedMetricUnitHours } from "./groupedmetricunithours";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class GroupedMetricUnitHoursPaged extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: GroupedMetricUnitHours })
    @Expose({ name: "data" })
    @Type(() => GroupedMetricUnitHours)
    data: GroupedMetricUnitHours[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    meta: Record<string, any>;
}
