/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GroupedCostHours } from "./groupedcosthours";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class GroupedCostHoursResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => GroupedCostHours)
    data: GroupedCostHours;
}
