/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GroupedMetricUnitHours } from "./groupedmetricunithours";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class GroupedMetricUnitHoursResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  @Type(() => GroupedMetricUnitHours)
  data: GroupedMetricUnitHours;
}
