/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GroupedUseMinuteHours } from "./groupeduseminutehours";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class GroupedUseMinuteHoursResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  @Type(() => GroupedUseMinuteHours)
  data: GroupedUseMinuteHours;
}
