/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GroupedValueHours } from "./groupedvaluehours";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class GroupedValueHoursList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: GroupedValueHours })
  @Expose({ name: "data" })
  @Type(() => GroupedValueHours)
  data: GroupedValueHours[];

  @SpeakeasyMetadata()
  @Expose({ name: "meta" })
  meta: Record<string, any>;
}
