/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GroupedUseMinuteHours } from "./groupeduseminutehours";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class GroupedUseMinuteHoursList extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: GroupedUseMinuteHours })
    @Expose({ name: "data" })
    @Type(() => GroupedUseMinuteHours)
    data: GroupedUseMinuteHours[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    meta: Record<string, any>;
}
