/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class Ingest extends SpeakeasyBase {
    /**
     * Soft-delete timestamp.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deleted_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    deletedAt?: Date;

    /**
     * Encoded data as stringified JSON or binary data that is base64 encoded.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "encoded" })
    encoded: string;

    /**
     * Ingest ID.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
