/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Ingest } from "./ingest";
import { Expose, Type } from "class-transformer";

/**
 * Request body for creating a single ingest.
 */
export class IngestCreateBody extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "ingest" })
  @Type(() => Ingest)
  ingest: Ingest;
}
