/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ApiKeyJsonPatchRequest extends SpeakeasyBase {
  /**
   * Request body with API key details as a JSON Patch.
   */
  @SpeakeasyMetadata({
    data: "request, media_type=application/json-patch+json",
  })
  apiKeyJsonPatchBody: shared.ApiKeyJsonPatchBody;

  /**
   * API key ID.
   */
  @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
  id: string;
}

export class ApiKeyJsonPatchResponse extends SpeakeasyBase {
  /**
   * Success
   */
  @SpeakeasyMetadata()
  apiKeyResponse?: shared.ApiKeyResponse;

  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Unprocessable Entity
   */
  @SpeakeasyMetadata()
  errorDetailResponse?: shared.ErrorDetailResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
