/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ApiKeyUpdatePutRequest extends SpeakeasyBase {
  /**
   * Request body with API key details.
   */
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  apiKeyUpdateBody: shared.ApiKeyUpdateBody;

  /**
   * API key ID.
   */
  @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
  id: string;
}

export class ApiKeyUpdatePutResponse extends SpeakeasyBase {
  /**
   * Success
   */
  @SpeakeasyMetadata()
  apiKeyResponse?: shared.ApiKeyResponse;

  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Unprocessable Entity
   */
  @SpeakeasyMetadata()
  errorDetailResponse?: shared.ErrorDetailResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
