/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class CustomerJsonPatchRequest extends SpeakeasyBase {
  /**
   * Request body with customer details as a JSON Patch.
   */
  @SpeakeasyMetadata({
    data: "request, media_type=application/json-patch+json",
  })
  customerJsonPatchBody: shared.CustomerJsonPatchBody;

  /**
   * Customer ID.
   */
  @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
  id: string;
}

export class CustomerJsonPatchResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Success
   */
  @SpeakeasyMetadata()
  customerResponse?: shared.CustomerResponse;

  /**
   * Unprocessable Entity
   */
  @SpeakeasyMetadata()
  errorDetailResponse?: shared.ErrorDetailResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
